name: docs_to_blogger
version: 1.0.1
description: Converts Google Docs output HTML to valid, idiomatic HTML5
author: Filip Hracek <filip.hracek@gmail.com>
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  args: any
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  html_unescape: ">=0.1.4 <1.0.0"
dev_dependencies:
  test: any
transformers:
- dart_to_js_script_rewriter
