library html_entities;

class HtmlEntities {
  
  static final Map<String,String> unsafeEntities = const {
    r"<" : "&lt;",
    r">" : "&gt;",
    r"&" : "&amp;"
  };
    
  static final Map<String,String> safeEntities = const {
    // from wikipedia: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
    "\"" : "&quot;",
    r"'" : "&apos;",

    //r" " : "&nbsp;",
    r"¡" : "&iexcl;",
    r"¢" : "&cent;",
    r"£" : "&pound;",
    r"¤" : "&curren;",
    r"¥" : "&yen;",
    r"¦" : "&brvbar;",
    r"§" : "&sect;",
    r"¨" : "&uml;",
    r"©" : "&copy;",
    r"ª" : "&ordf;",
    r"«" : "&laquo;",
    r"¬" : "&not;",
    //r" " : "&shy;",
    r"®" : "&reg;",
    r"¯" : "&macr;",
    r"°" : "&deg;",
    r"±" : "&plusmn;",
    r"²" : "&sup2;",
    r"³" : "&sup3;",
    r"´" : "&acute;",
    r"µ" : "&micro;",
    r"¶" : "&para;",
    r"·" : "&middot;",
    r"¸" : "&cedil;",
    r"¹" : "&sup1;",
    r"º" : "&ordm;",
    r"»" : "&raquo;",
    r"¼" : "&frac14;",
    r"½" : "&frac12;",
    r"¾" : "&frac34;",
    r"¿" : "&iquest;",
    r"À" : "&Agrave;",
    r"Á" : "&Aacute;",
    r"Â" : "&Acirc;",
    r"Ã" : "&Atilde;",
    r"Ä" : "&Auml;",
    r"Å" : "&Aring;",
    r"Æ" : "&AElig;",
    r"Ç" : "&Ccedil;",
    r"È" : "&Egrave;",
    r"É" : "&Eacute;",
    r"Ê" : "&Ecirc;",
    r"Ë" : "&Euml;",
    r"Ì" : "&Igrave;",
    r"Í" : "&Iacute;",
    r"Î" : "&Icirc;",
    r"Ï" : "&Iuml;",
    r"Ð" : "&ETH;",
    r"Ñ" : "&Ntilde;",
    r"Ò" : "&Ograve;",
    r"Ó" : "&Oacute;",
    r"Ô" : "&Ocirc;",
    r"Õ" : "&Otilde;",
    r"Ö" : "&Ouml;",
    r"×" : "&times;",
    r"Ø" : "&Oslash;",
    r"Ù" : "&Ugrave;",
    r"Ú" : "&Uacute;",
    r"Û" : "&Ucirc;",
    r"Ü" : "&Uuml;",
    r"Ý" : "&Yacute;",
    r"Þ" : "&THORN;",
    r"ß" : "&szlig;",
    r"à" : "&agrave;",
    r"á" : "&aacute;",
    r"â" : "&acirc;",
    r"ã" : "&atilde;",
    r"ä" : "&auml;",
    r"å" : "&aring;",
    r"æ" : "&aelig;",
    r"ç" : "&ccedil;",
    r"è" : "&egrave;",
    r"é" : "&eacute;",
    r"ê" : "&ecirc;",
    r"ë" : "&euml;",
    r"ì" : "&igrave;",
    r"í" : "&iacute;",
    r"î" : "&icirc;",
    r"ï" : "&iuml;",
    r"ð" : "&eth;",
    r"ñ" : "&ntilde;",
    r"ò" : "&ograve;",
    r"ó" : "&oacute;",
    r"ô" : "&ocirc;",
    r"õ" : "&otilde;",
    r"ö" : "&ouml;",
    r"÷" : "&divide;",
    r"ø" : "&oslash;",
    r"ù" : "&ugrave;",
    r"ú" : "&uacute;",
    r"û" : "&ucirc;",
    r"ü" : "&uuml;",
    r"ý" : "&yacute;",
    r"þ" : "&thorn;",
    r"ÿ" : "&yuml;",
    r"Œ" : "&OElig;",
    r"œ" : "&oelig;",
    r"Š" : "&Scaron;",
    r"š" : "&scaron;",
    r"Ÿ" : "&Yuml;",
    r"ƒ" : "&fnof;",
    r"ˆ" : "&circ;",
    r"˜" : "&tilde;",
    r"Α" : "&Alpha;",
    r"Β" : "&Beta;",
    r"Γ" : "&Gamma;",
    r"Δ" : "&Delta;",
    r"Ε" : "&Epsilon;",
    r"Ζ" : "&Zeta;",
    r"Η" : "&Eta;",
    r"Θ" : "&Theta;",
    r"Ι" : "&Iota;",
    r"Κ" : "&Kappa;",
    r"Λ" : "&Lambda;",
    r"Μ" : "&Mu;",
    r"Ν" : "&Nu;",
    r"Ξ" : "&Xi;",
    r"Ο" : "&Omicron;",
    r"Π" : "&Pi;",
    r"Ρ" : "&Rho;",
    r"Σ" : "&Sigma;",
    r"Τ" : "&Tau;",
    r"Υ" : "&Upsilon;",
    r"Φ" : "&Phi;",
    r"Χ" : "&Chi;",
    r"Ψ" : "&Psi;",
    r"Ω" : "&Omega;",
    r"α" : "&alpha;",
    r"β" : "&beta;",
    r"γ" : "&gamma;",
    r"δ" : "&delta;",
    r"ε" : "&epsilon;",
    r"ζ" : "&zeta;",
    r"η" : "&eta;",
    r"θ" : "&theta;",
    r"ι" : "&iota;",
    r"κ" : "&kappa;",
    r"λ" : "&lambda;",
    r"μ" : "&mu;",
    r"ν" : "&nu;",
    r"ξ" : "&xi;",
    r"ο" : "&omicron;",
    r"π" : "&pi;",
    r"ρ" : "&rho;",
    r"ς" : "&sigmaf;",
    r"σ" : "&sigma;",
    r"τ" : "&tau;",
    r"υ" : "&upsilon;",
    r"φ" : "&phi;",
    r"χ" : "&chi;",
    r"ψ" : "&psi;",
    r"ω" : "&omega;",
    r"ϑ" : "&thetasym;",
    r"ϒ" : "&upsih;",
    r"ϖ" : "&piv;",
    //r" " : "&ensp;",
    //r" " : "&emsp;",
    //r" " : "&thinsp;",
    //r" " : "&zwnj;",
    //r" " : "&zwj;",
    //r" " : "&lrm;",
    //r" " : "&rlm;",
    r"–" : "&ndash;",
    r"—" : "&mdash;",
    r"‘" : "&lsquo;",
    r"’" : "&rsquo;",
    r"‚" : "&sbquo;",
    r"“" : "&ldquo;",
    r"”" : "&rdquo;",
    r"„" : "&bdquo;",
    r"†" : "&dagger;",
    r"‡" : "&Dagger;",
    r"•" : "&bull;",
    r"…" : "&hellip;",
    r"‰" : "&permil;",
    r"′" : "&prime;",
    r"″" : "&Prime;",
    r"‹" : "&lsaquo;",
    r"›" : "&rsaquo;",
    r"‾" : "&oline;",
    r"⁄" : "&frasl;",
    r"€" : "&euro;",
    r"ℑ" : "&image;",
    r"℘" : "&weierp;",
    r"ℜ" : "&real;",
    r"™" : "&trade;",
    r"ℵ" : "&alefsym;",
    r"←" : "&larr;",
    r"↑" : "&uarr;",
    r"→" : "&rarr;",
    r"↓" : "&darr;",
    r"↔" : "&harr;",
    r"↵" : "&crarr;",
    r"⇐" : "&lArr;",
    r"⇑" : "&uArr;",
    r"⇒" : "&rArr;",
    r"⇓" : "&dArr;",
    r"⇔" : "&hArr;",
    r"∀" : "&forall;",
    r"∂" : "&part;",
    r"∃" : "&exist;",
    r"∅" : "&empty;",
    r"∇" : "&nabla;",
    r"∈" : "&isin;",
    r"∉" : "&notin;",
    r"∋" : "&ni;",
    r"∏" : "&prod;",
    r"∑" : "&sum;",
    r"−" : "&minus;",
    r"∗" : "&lowast;",
    r"√" : "&radic;",
    r"∝" : "&prop;",
    r"∞" : "&infin;",
    r"∠" : "&ang;",
    r"∧" : "&and;",
    r"∨" : "&or;",
    r"∩" : "&cap;",
    r"∪" : "&cup;",
    r"∫" : "&int;",
    r"∴" : "&there4;",
    r"∼" : "&sim;",
    r"≅" : "&cong;",
    r"≈" : "&asymp;",
    r"≠" : "&ne;",
    r"≡" : "&equiv;",
    r"≤" : "&le;",
    r"≥" : "&ge;",
    r"⊂" : "&sub;",
    r"⊃" : "&sup;",
    r"⊄" : "&nsub;",
    r"⊆" : "&sube;",
    r"⊇" : "&supe;",
    r"⊕" : "&oplus;",
    r"⊗" : "&otimes;",
    r"⊥" : "&perp;",
    r"⋅" : "&sdot;",
    r"⌈" : "&lceil;",
    r"⌉" : "&rceil;",
    r"⌊" : "&lfloor;",
    r"⌋" : "&rfloor;",
    r"〈" : "&lang;",
    r"〉" : "&rang;",
    r"◊" : "&loz;",
    r"♠" : "&spades;",
    r"♣" : "&clubs;",
    r"♥" : "&hearts;",
    r"♦" : "&diams;",

    // http://tlt.its.psu.edu/suggestions/international/bylanguage/czechslovak.html#htmlcodes
    // CZECH
    r"Č" : "&#268;",
    r"č" : "&#269;",
    r"Ď" : "&#270;",
    r"ď" : "&#271;",
    r"Ľ" : "&#317;",
    r"ľ" : "&#318;",
    r"Ň" : "&#327;",
    r"ň" : "&#328;",
    r"Ř" : "&#344;",
    r"ř" : "&#345;",
//    r"Š" : "&#352;",
//    r"š" : "&#353;",
    r"Ť" : "&#356;",
    r"ť" : "&#357;",
    r"Ž" : "&#381;",
    r"ž" : "&#382;",
    r"Ů" : "&#366;",
    r"ů" : "&#367;",
//    r"Ä" : "&Auml;",
//    r"ä" : "&auml;",
    r"Ě" : "&#282;",
    r"ě" : "&#283;",
//    r"Ô" : "&Ocirc;",
//    r"ô" : "&ocirc;",
    r"Ĺ" : "&#313;",
    r"ĺ" : "&#314;",
    r"Ŕ" : "&#340;",
    r"ŕ" : "&#341;"
  };
  
  static final Map<String,String> safeEntitiesSubset = const {
    // from wikipedia: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
    "\"" : "&quot;",
    r"'" : "&apos;",

    r"À" : "&Agrave;",
    r"Á" : "&Aacute;",
    r"Â" : "&Acirc;",
    r"Ã" : "&Atilde;",
    r"Ä" : "&Auml;",
    r"Å" : "&Aring;",
    r"Æ" : "&AElig;",
    r"Ç" : "&Ccedil;",
    r"È" : "&Egrave;",
    r"É" : "&Eacute;",
    r"Ê" : "&Ecirc;",
    r"Ë" : "&Euml;",
    r"Ì" : "&Igrave;",
    r"Í" : "&Iacute;",
    r"Î" : "&Icirc;",
    r"Ï" : "&Iuml;",
    r"Ð" : "&ETH;",
    r"Ñ" : "&Ntilde;",
    r"Ò" : "&Ograve;",
    r"Ó" : "&Oacute;",
    r"Ô" : "&Ocirc;",
    r"Õ" : "&Otilde;",
    r"Ö" : "&Ouml;",
    r"×" : "&times;",
    r"Ø" : "&Oslash;",
    r"Ù" : "&Ugrave;",
    r"Ú" : "&Uacute;",
    r"Û" : "&Ucirc;",
    r"Ü" : "&Uuml;",
    r"Ý" : "&Yacute;",
    r"Þ" : "&THORN;",
    r"ß" : "&szlig;",
    r"à" : "&agrave;",
    r"á" : "&aacute;",
    r"â" : "&acirc;",
    r"ã" : "&atilde;",
    r"ä" : "&auml;",
    r"å" : "&aring;",
    r"æ" : "&aelig;",
    r"ç" : "&ccedil;",
    r"è" : "&egrave;",
    r"é" : "&eacute;",
    r"ê" : "&ecirc;",
    r"ë" : "&euml;",
    r"ì" : "&igrave;",
    r"í" : "&iacute;",
    r"î" : "&icirc;",
    r"ï" : "&iuml;",
    r"ð" : "&eth;",
    r"ñ" : "&ntilde;",
    r"ò" : "&ograve;",
    r"ó" : "&oacute;",
    r"ô" : "&ocirc;",
    r"õ" : "&otilde;",
    r"ö" : "&ouml;",
    r"÷" : "&divide;",
    r"ø" : "&oslash;",
    r"ù" : "&ugrave;",
    r"ú" : "&uacute;",
    r"û" : "&ucirc;",
    r"ü" : "&uuml;",
    r"ý" : "&yacute;",
    r"þ" : "&thorn;",
    r"ÿ" : "&yuml;",
    r"Œ" : "&OElig;",
    r"œ" : "&oelig;",
    r"Š" : "&Scaron;",
    r"š" : "&scaron;",
    r"Ÿ" : "&Yuml;",
    r"ƒ" : "&fnof;",

    r"—" : "&mdash;",
    r"‘" : "&lsquo;",
    r"’" : "&rsquo;",
    r"‚" : "&sbquo;",
    r"“" : "&ldquo;",
    r"”" : "&rdquo;",
    r"„" : "&bdquo;",

    r"…" : "&hellip;",

    r"′" : "&prime;",
    r"″" : "&Prime;",
    r"‹" : "&lsaquo;",
    r"›" : "&rsaquo;",

    r"€" : "&euro;",

    r"™" : "&trade;",

    r"←" : "&larr;",
    r"↑" : "&uarr;",
    r"→" : "&rarr;",
    r"↓" : "&darr;",
    r"↔" : "&harr;",
    r"↵" : "&crarr;",
    r"⇐" : "&lArr;",
    r"⇑" : "&uArr;",
    r"⇒" : "&rArr;",
    r"⇓" : "&dArr;",
    r"⇔" : "&hArr;",

    // CZECH
    r"Č" : "&#268;",
    r"č" : "&#269;",
    r"Ď" : "&#270;",
    r"ď" : "&#271;",
    r"Ľ" : "&#317;",
    r"ľ" : "&#318;",
    r"Ň" : "&#327;",
    r"ň" : "&#328;",
    r"Ř" : "&#344;",
    r"ř" : "&#345;",
//    r"Š" : "&#352;",
//    r"š" : "&#353;",
    r"Ť" : "&#356;",
    r"ť" : "&#357;",
    r"Ž" : "&#381;",
    r"ž" : "&#382;",
    r"Ů" : "&#366;",
    r"ů" : "&#367;",
//    r"Ä" : "&Auml;",
//    r"ä" : "&auml;",
    r"Ě" : "&#282;",
    r"ě" : "&#283;",
//    r"Ô" : "&Ocirc;",
//    r"ô" : "&ocirc;",
    r"Ĺ" : "&#313;",
    r"ĺ" : "&#314;",
    r"Ŕ" : "&#340;",
    r"ŕ" : "&#341;"

  };
  
  static final Map<String,String> safeEntitiesToCharsSubset = const {
    // from wikipedia: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
    "\"" : "&quot;",
    "&apos;" : r"'",
    
    "&Agrave;" : r"À",
    "&Aacute;" : r"Á",
    "&Acirc;" : r"Â",
    "&Atilde;" : r"Ã",
    "&Auml;" : r"Ä",
    "&Aring;" : r"Å",
    "&AElig;" : r"Æ",
    "&Ccedil;" : r"Ç",
    "&Egrave;" : r"È",
    "&Eacute;" : r"É",
    "&Ecirc;" : r"Ê",
    "&Euml;" : r"Ë",
    "&Igrave;" : r"Ì",
    "&Iacute;" : r"Í",
    "&Icirc;" : r"Î",
    "&Iuml;" : r"Ï",
    "&ETH;" : r"Ð",
    "&Ntilde;" : r"Ñ",
    "&Ograve;" : r"Ò",
    "&Oacute;" : r"Ó",
    "&Ocirc;" : r"Ô",
    "&Otilde;" : r"Õ",
    "&Ouml;" : r"Ö",
    "&times;" : r"×",
    "&Oslash;" : r"Ø",
    "&Ugrave;" : r"Ù",
    "&Uacute;" : r"Ú",
    "&Ucirc;" : r"Û",
    "&Uuml;" : r"Ü",
    "&Yacute;" : r"Ý",
    "&THORN;" : r"Þ",
    "&szlig;" : r"ß",
    "&agrave;" : r"à",
    "&aacute;" : r"á",
    "&acirc;" : r"â",
    "&atilde;" : r"ã",
    "&auml;" : r"ä",
    "&aring;" : r"å",
    "&aelig;" : r"æ",
    "&ccedil;" : r"ç",
    "&egrave;" : r"è",
    "&eacute;" : r"é",
    "&ecirc;" : r"ê",
    "&euml;" : r"ë",
    "&igrave;" : r"ì",
    "&iacute;" : r"í",
    "&icirc;" : r"î",
    "&iuml;" : r"ï",
    "&eth;" : r"ð",
    "&ntilde;" : r"ñ",
    "&ograve;" : r"ò",
    "&oacute;" : r"ó",
    "&ocirc;" : r"ô",
    "&otilde;" : r"õ",
    "&ouml;" : r"ö",
    "&divide;" : r"÷",
    "&oslash;" : r"ø",
    "&ugrave;" : r"ù",
    "&uacute;" : r"ú",
    "&ucirc;" : r"û",
    "&uuml;" : r"ü",
    "&yacute;" : r"ý",
    "&thorn;" : r"þ",
    "&yuml;" : r"ÿ",
    "&OElig;" : r"Œ",
    "&oelig;" : r"œ",
    "&Scaron;" : r"Š",
    "&scaron;" : r"š",
    "&Yuml;" : r"Ÿ",
    "&fnof;" : r"ƒ",
    
    "&mdash;" : r"—",
    "&lsquo;" : r"‘",
    "&rsquo;" : r"’",
    "&sbquo;" : r"‚",
    "&ldquo;" : r"“",
    "&rdquo;" : r"”",
    "&bdquo;" : r"„",
    
    "&hellip;" : r"…",
    
    "&prime;" : r"′",
    "&Prime;" : r"″",
    "&lsaquo;" : r"‹",
    "&rsaquo;" : r"›",
    
    "&euro;" : r"€",
    
    "&trade;" : r"™",
    
    "&larr;" : r"←",
    "&uarr;" : r"↑",
    "&rarr;" : r"→",
    "&darr;" : r"↓",
    "&harr;" : r"↔",
    "&crarr;" : r"↵",
    "&lArr;" : r"⇐",
    "&uArr;" : r"⇑",
    "&rArr;" : r"⇒",
    "&dArr;" : r"⇓",
    "&hArr;" : r"⇔",
    
    // CZECH
    "&#268;" : r"Č",
    "&#269;" : r"č",
    "&#270;" : r"Ď",
    "&#271;" : r"ď",
    "&#317;" : r"Ľ",
    "&#318;" : r"ľ",
    "&#327;" : r"Ň",
    "&#328;" : r"ň",
    "&#344;" : r"Ř",
    "&#345;" : r"ř",
    //"&#352;" : r"Š",
    //"&#353;" : r"š",
    "&#356;" : r"Ť",
    "&#357;" : r"ť",
    "&#381;" : r"Ž",
    "&#382;" : r"ž",
    "&#366;" : r"Ů",
    "&#367;" : r"ů",
    //"&Auml;" : r"Ä",
    //"&auml;" : r"ä",
    "&#282;" : r"Ě",
    "&#283;" : r"ě",
    //"&Ocirc;" : r"Ô",
    //"&ocirc;" : r"ô",
    "&#313;" : r"Ĺ",
    "&#314;" : r"ĺ",
    "&#340;" : r"Ŕ",
    "&#341;" : r"ŕ"
  };
  
  

  static String toHtml(String s) {
    unsafeEntities.forEach((charUtf, entity) {
        s = s.replaceAll(charUtf, entity);
    });    
    safeEntities.forEach((charUtf, entity) {
        s = s.replaceAll(charUtf, entity);
    });
    return s;
  }
  
  static final RegExp _htmlEntity = new RegExp(r"&(\w{2,8}|#\d{2,4});");
  
  static String collapseSafeEntities(String input, {bool useAll: true}) {
//    var entities = (useAll ? safeEntities : safeEntitiesSubset);
//    safeEntities.forEach((charUtf, entity) {
//      s = s.replaceAll(entity, charUtf);
//    });
    
    StringBuffer strBuf = new StringBuffer();
    int index = 0;

    // find <span class="c2">...</span> and convert to <strong>...</strong>
    Match m = _htmlEntity.firstMatch(input);
    while (m != null) {
      strBuf.write(input.substring(index,index + m.start));

      if (safeEntitiesToCharsSubset.containsKey(m.group(0))) {
        strBuf.write(safeEntitiesToCharsSubset[m.group(0)]);
      } else {
        strBuf.write(m.group(0));
      }

      index = index + m.end;
      m = _htmlEntity.firstMatch(input.substring(index));
    }
    
    // add the rest
    strBuf.write(input.substring(index));
    
    return strBuf.toString();
  }
}
